### ISSUE TITLE
long bars between each update

### ISSUE THREAD

**Issue by jvluso** [clo-yunhee/speech-analysis#10]
When I try to run it there's 1/4-1 sec between each time it analyzes any sound producing long bars on the spectrograph. I'm running the 1.5.7 linux release. I'm not seeing any limitations in memory or in cpu usage.

**Comment by clo-yunhee** [comment]
What audio backend are you using on your Linux installation?

**Comment by jvluso** [comment]
The new version solved the problem. I'm using Ubuntu with pulse audio drivers. Thank you.
