### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by nicetranslady** [clo-yunhee/speech-analysis#6]
Hi, is there a precompiled version of code for Mac? I've seen that some comments have been made, but although I have VS 2019 for Mac and obvs xCode, I have no idea what to do to compile them. Are there any pointers (pardon the pun), or links that may help?

Thanks,
Holly

**Comment by ichi-rika** [comment]
Hey!

There's no precompiled version for OS X because I don't own a Mac.

FYI, I compile both Windows and Linux packages from a Linux environment, and I do want to get an OS X compiler set up eventually, but Qt is a pain to cross-compile from Linux to OS X and that complicates things quite a lot :/

For the time being, I'd recommend using [Release 1.3](https://github.com/ichi-rika/speech-analysis/releases/tag/v1.3) with Wine, as the later versions don't work well with Wine.

Sorry for the inconvenience, I'm still trying to make this work ^ ^ '

**Comment by holls77** [comment]
OK. NP. Thanks for the response.
Holly x

**Comment by sophiyarap** [comment]
Thanks for the new Mac build! I am not sure how to open this because it seems OSX is not a valid extension.

**Comment by PushoN** [comment]
Nothing happened when try to open .dmg file on Mac OS 10.13.6.

**Comment by holls77** [comment]
Hiya,
Thanks so much for getting a Mac version going. Version 10.15.4 (Catalina)

For reference and how to get it to run...
Once you've double clicked it, you should get an Icon on your desktop named  "Install"
Open it and you'll see "SpeechAnalysis.spp" drag this into your Applications folder.
Go into your applications folder, right-click and choose open - this will give you the option to open it even though Apple can't scan it it for malware.
On opening, you'll have to approve the use of your Microphone.
You can now "Eject" the "Install" icon from your desktop.

I kno what I'm doing tonight! xx

**Comment by PushoN** [comment]
> Hiya,
> Thanks so much for getting a Mac version going.
> 
> For reference and how to get it to run on Version 10.15.4 (Catalina) ...
> Following downloading...
> 
> 1. Once you've double clicked "out.OSG.dmg", you should get an icon on your desktop named  "Install".
> 2. Open it and you'll see "SpeechAnalysis.spp" drag this into your Applications folder.
> 3. Go into your applications folder, right-click and choose open - this will give you the option to open it even though Apple can't scan it it for malware.
> 4. On opening, you'll have to approve the use of your Microphone.
> 5. You can now "Eject" the "Install" icon from your desktop.
> 
> I know what I'm going to be doing tonight! xx

thank you very much! my fault that i expected to see something , cheers!

**Comment by sophiyarap** [comment]
Hi @ichi-rika, Mac version crashes on open in the latest version 1.5.5, Just fyi. Thanks.

**Comment by ichi-rika** [comment]
Hey, @sophiyarap 
Please open a new issue next time you encounter a new problem \^-\^
The latest release (1.5.6) should have fixed that crash, please report if it still crashes
